### ISSUE TITLE
Beginner Learning Path

### ISSUE THREAD

**Issue by jacobcreech** [solana-developers/developer-experience#12]
There needs to be a learning path for developers that have almost 0 experience and can start on Solana.

Should be able to get beginners started(think university level) on creating something simple, while walking through querying on-chain data, PDAs, and CPI as part of the path.

**Comment by buffalojoec** [comment]
I'd be down to put together some in-depth "Zero to Hero" courses. We could have a few different tutorials for a few cool applications and do a blog-post-style step-by-step walkthrough with an associated video tutorial as well?
One key aspect would be finding some common web2 build patterns - like a Twitter backend or some kind of API - so that people are comfortable with the context
